#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Configure Nginx to add the custom response header
sudo sed -i '/server {/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart

